spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yooxinz/springCloudConfig
          search-paths: spring-cloud-study/config-mac-mysql
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/